#!/bin/bash
echo "DB=$MY_DB"
echo "JWTPRIVATEKEY=$MY_JWTPRIVATEKEY"
echo "SALT = $MY_SALT"
echo "RAZORPAY_KEY_ID=$MY_RAZORPAY_KEY_ID"
echo "RAZORPAY_KEY_SECRET=$MY_RAZORPAY_KEY_SECRET"

echo "CLOUDNARY_API_KEY=$MY_CLOUDNARY_API_KEY"
echo "CLOUDNARY_API_SECREAT=$MY_CLOUDNARY_API_SECREAT"
echo "CLOUDNARY_API_NAME=$MY_CLOUDNARY_API_NAME"