version: "1"
services:
  frontend:
    image: amangupta2992/locally-frontend
    stdin_open: true
    ports:
      - "5173:5173"
    networks:
      - locally
  api-server:
    image: amangupta2992/locally-backend
    ports:
      - "8080:8080"
    depends_on:
      - redis-server
    networks:
      - locally
  redis-server:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - locally
networks:
  locally:
    driver: bridge  





