name: Unit Tests

on: [pull_request]

jobs:
    tests:
        runs-on: ubuntu-latest
        env:
          MY_SALT: ${{ vars.SALT }}
        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                node-version: ${{ matrix.node-version }}
            - name: npm intsall
              run: npm ci
            - name: Manage .env
              run: source cicd.sh
            - name: tests
              run: npm test